services:
  web:
    build: .
    container_name: phlaw_backend
    ports:
      - "8000:8000"
      - "7860:7860"
    volumes:
      - ./model_cache:/root/.cache/huggingface  # Only model cache, NOT full backend
      - ./backend/jurisprudence:/app/backend/jurisprudence  # ✅ Add this line
    env_file:
      - ./backend/.env
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
