version: '3.8'

services:
  # Backend service (Django)
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile  # Path to the backend Dockerfile
    container_name: phlaw_backend
    ports:
      - "8000:8000"  # Django backend
      - "7860:7860"  # For GPU services
    volumes:
      - ./model_cache:/root/.cache/huggingface
      - ./backend:/app/backend
    env_file:
      - ./backend/.env
    depends_on:
      - qdrant  # Ensure Qdrant is up before backend starts
    runtime: nvidia  # GPU support
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # GPU usage

  # Frontend service (Next.js)
  frontend:
    build:
      context: . # Path to the frontend directory
      dockerfile: frontend/Dockerfile  # The Dockerfile inside the frontend directory
    container_name: phlaw_frontend
    ports:
      - "3000:3000"  # Next.js default port
    volumes:
      - ./frontend:/app/frontend  # Sync frontend code
    command: npm run dev  # Start Next.js development server
    depends_on:
      - web  # Ensure backend is up before frontend starts

  # Qdrant service (if needed)
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"  # Default Qdrant port
    volumes:
      - qdrant_data:/qdrant/storage

# Named volumes
volumes:
  qdrant_data:  # For persistent Qdrant storage
