services:
  web:
    build: .
    container_name: phlaw_backend
    ports:
      - "8000:8000"
      - "7860:7860"
    volumes:
      - ./backend:/app/backend
      - ./model_cache:/root/.cache/huggingface
    env_file:
      - ./backend/.env
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

