services:
  web:
    build: .
    container_name: phlaw_backend
    ports:
      - "8000:8000"
      - "7860:7860"
    volumes:
      - ./model_cache:/root/.cache/huggingface
      - ./backend:/app/backend
      # - ./law-chat.Q5_K_M.gguf:/app/law-chat.Q5_K_M.gguf  # If model outside backend
    env_file:
      - ./backend/.env
    depends_on:
      - qdrant
    runtime: nvidia                # <-- for GPU
    environment:
      - NVIDIA_VISIBLE_DEVICES=all # <-- for GPU

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
